name: ddamsproteomics-2.7
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::msgf_plus=2020.03.14
  - bioconda::proteowizard=3_0_9992=h2d50403_2
  - bioconda::hardklor=2.3.2
  - bioconda::kronik=2.20
  - bioconda::dinosaur=1.2.0
  - bioconda::openms=2.5.0
  - bioconda::msstitch=3.9
  - conda-forge::biopython=1.72
  - bioconda::percolator=3.4
  - bioconda::luciphor2=2020_04_03
  - conda-forge::lxml=4.2.5
  - conda-forge::jinja2=2.10
  - conda-forge::r-argparse=2.0.1
  - conda-forge::r-ggplot2=3.3.1
  - conda-forge::r-ggrepel=0.8.2
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-forcats=0.5.0
  - conda-forge::r-markdown=1.1
  - conda-forge::r-matrixstats=0.56.0
  - bioconda::bioconductor-deqms=1.6.0
  - conda-forge::r-cairo=1.5_12
